# web
server:
  port: 8081

config:
  user:
    name: Mr.Li
    age: 27
    sex: 男
    key: @config.key@
    value: @config.value@
  application: 單車



spring:
  # 模板配置
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    pool.max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    pool.max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-idle: 8 # 连接池中的最大空闲连接
    pool.min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）



